/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_unidbg_arm_backend_HypervisorFactory */

#ifndef _Included_com_github_unidbg_arm_backend_HypervisorFactory
#define _Included_com_github_unidbg_arm_backend_HypervisorFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_unidbg_arm_backend_HypervisorFactory
 * Method:    testVcpu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_unidbg_arm_backend_HypervisorFactory_testVcpu
  (JNIEnv *, jclass);

/*
 * Class:     com_github_unidbg_arm_backend_HypervisorFactory
 * Method:    getPageSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_unidbg_arm_backend_HypervisorFactory_getPageSize
  (JNIEnv *, jclass);

/*
 * Class:     com_github_unidbg_arm_backend_HypervisorFactory
 * Method:    getMaxVcpuCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_unidbg_arm_backend_HypervisorFactory_getMaxVcpuCount
  (JNIEnv *, jclass);

/*
 * Class:     com_github_unidbg_arm_backend_HypervisorFactory
 * Method:    sysctlInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_unidbg_arm_backend_HypervisorFactory_sysctlInt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_unidbg_arm_backend_HypervisorFactory
 * Method:    context_alloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_unidbg_arm_backend_HypervisorFactory_context_1alloc
  (JNIEnv *, jclass);

/*
 * Class:     com_github_unidbg_arm_backend_HypervisorFactory
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_unidbg_arm_backend_HypervisorFactory_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
