/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_unidbg_arm_backend_unicorn_Unicorn_Tuple */

#ifndef _Included_com_github_unidbg_arm_backend_unicorn_Unicorn_Tuple
#define _Included_com_github_unidbg_arm_backend_unicorn_Unicorn_Tuple
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
