/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_unidbg_android_JniTest */

#ifndef _Included_com_github_unidbg_android_JniTest
#define _Included_com_github_unidbg_android_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_unidbg_android_JniTest
 * Method:    testJni
 * Signature: (Ljava/lang/String;JIDZSFDBJF)V
 */
JNIEXPORT void JNICALL Java_com_github_unidbg_android_JniTest_testJni
  (JNIEnv *, jclass, jstring, jlong, jint, jdouble, jboolean, jshort, jfloat, jdouble, jbyte, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
